# __*Python NumPy Theory*__

## 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy (Numerical Python) is a powerful library that enhances Python’s capabilities for scientific computing and data analysis. Its core feature is the N-dimensional array (ndarray), which allows efficient storage and manipulation of large datasets, offering significant performance improvements over Python’s built-in data structures like lists. Here's how NumPy contributes to scientific computing:

### 1. __Purpose of NumPy:__
- __Efficient numerical operations:__ NumPy is designed for fast and efficient numerical computations. It allows operations like addition, multiplication, and other mathematical functions to be performed element-wise on arrays.
- __Multi-dimensional arrays:__ Provides support for large, multi-dimensional arrays and matrices, which are essential in scientific computing.
- __Mathematical functions and linear algebra:__ Includes numerous built-in mathematical functions such as trigonometric, statistical, and algebraic operations that are optimized for speed.
- __Interoperability:__ It integrates easily with other scientific computing libraries like SciPy, Pandas, and matplotlib, enhancing Python’s ecosystem for data analysis and visualization.
- __Efficient memory usage:__ NumPy arrays are more compact and efficient than Python lists or tuples, consuming less memory.
### 2. __Advantages of NumPy:__
- __Performance improvement:__ NumPy arrays use contiguous memory blocks, allowing for fast and vectorized operations without the need for Python loops, which significantly speeds up numerical computations.
- __Broadcasting:__ This feature allows NumPy to perform arithmetic operations on arrays of different shapes in an element-wise manner without explicitly reshaping or replicating data, simplifying code and improving performance.
- __Vectorized operations:__ NumPy supports vectorized operations, allowing you to apply functions to entire arrays without the need for explicit loops, leading to cleaner and faster code.
- __Multi-dimensional slicing:__ Arrays can be sliced in multiple dimensions, making it easier to extract and manipulate subsets of the data.
- __Support for scientific functions:__ NumPy provides functions for matrix operations, Fourier transforms, random number generation, and many other scientific tasks, making it a cornerstone for scientific computing.
- __Ease of integration with C/C++ and Fortran:__ NumPy arrays can be used in conjunction with C or Fortran code, making it easy to speed up critical parts of code.
### 3. __Enhancement of Python’s Numerical Capabilities:__
- __Optimized for large-scale data:__ With its efficient data structures and operations, NumPy allows Python to handle large datasets and perform complex computations that would be slower or more cumbersome using native Python.
- __Faster computation for numerical operations:__ Since NumPy is implemented in C and optimized for performance, it dramatically accelerates tasks such as matrix multiplication, statistical analysis, and numerical simulation.
- __Mathematical consistency:__ It ensures consistent and accurate floating-point operations, which are critical in scientific analysis.

## 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the  other?

Both `np.mean()` and `np.average()` in NumPy are used to compute the average of elements in an array, but they have subtle differences in functionality, particularly regarding the use of weights. Here's a detailed comparison:

### 1. __np.mean():__
- __Purpose:__ It calculates the arithmetic mean (simple average) of the array elements.
- __Syntax:__ `np.mean(a, axis=None, dtype=None, out=None, keepdims=False)`
- __Weights:__ `np.mean()` does not accept weights. It computes the mean by summing all elements and dividing by the number of elements.
- __Axis argument:__ You can specify the axis along which to compute the mean.
    - If `axis=None`, it computes the mean of all elements in the array (global mean).
    - If `axis=0` or `axis=1`, it computes the mean along that axis (e.g., column-wise or row-wise for 2D arrays).
- __When to use:__ Use `np.mean()` when you need to compute the simple, unweighted average of your data.

### 2. __np.average():__
- __Purpose:__ It calculates a weighted average of the array elements. If no weights are provided, it defaults to the arithmetic mean, similar to np.mean().
- __Syntax:__ `np.average(a, axis=None, weights=None, returned=False)`
- __Weights:__ `np.average()` can accept an optional weights argument. This allows you to assign different importance (weights) to each element when calculating the average.
    - If `weights=None`, it behaves like `np.mean()`.
    - If weights are provided, it computes the weighted sum of elements divided by the sum of the weights.
- __Axis argument:__ Similar to `np.mean()`, you can specify the axis along which to compute the average.
- __Returned argument:__ If `returned=True`, it returns a tuple where the second value is the sum of the weights.
- __When to use:__ Use `np.average()` when you need a weighted average, where certain elements contribute more to the average than others.

### 3. __When to Use One Over the Other:__
__Use `np.mean()`:__
- When you want the simple arithmetic mean of the data.
- When there are no weights involved in the calculation.
- When you want a more concise and straightforward function call for calculating the mean.
__Use `np.average()`:__
- When you need a weighted average where different elements contribute differently based on the given weights.
- When you want the sum of the weights alongside the average (by using returned=True).

### 4. __Example:__
Let's say we have four exam scores for a student and each exam has a different weight (importance) in the final grade. The student's scores and the exam weights are as follows:

- Scores: [85, 90, 80, 95]
- Weights: [0.2, 0.3, 0.1, 0.4]

In [4]:
import numpy as np

# Scores and weights
scores = np.array([85, 90, 80, 95])
weights = np.array([0.2, 0.3, 0.1, 0.4])

# Simple mean (without weights)
mean_result = np.mean(scores)

# Weighted average (with weights)
weighted_average = np.average(scores, weights=weights)

print("Mean (Simple Average):", mean_result)
print("Weighted Average:", weighted_average)


Mean (Simple Average): 87.5
Weighted Average: 90.0


## 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D  arrays.

Reversing a NumPy array involves flipping the elements of the array along a particular axis. There are multiple methods for reversing a NumPy array, and the approach depends on the dimensionality (1D, 2D, etc.) and the specific axis along which you want to reverse the array.

### __Methods to Reverse a NumPy Array:__
1. __Using Slicing ([::-1]):__
The simplest and most common way to reverse an array is by using slicing. The slice [::-1] reverses the array along a given axis.
2. __Using np.flip():__
The np.flip() function reverses the array along a specified axis. It is more flexible than slicing and works for both 1D and higher-dimensional arrays.
3. __Using np.flipud() (Flip Up-Down):__
This function is specifically for flipping an array vertically (i.e., along the first axis). It is commonly used for 2D arrays.
4. __Using np.fliplr() (Flip Left-Right):__
This function is used for flipping an array horizontally (i.e., along the second axis in 2D arrays).


In [5]:
# Reversing a 1D Array
# Using Slicing ([::-1]):

import numpy as np

# 1D Array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse using slicing
reversed_1d = arr_1d[::-1]

print("Original 1D Array:", arr_1d)
print("Reversed 1D Array:", reversed_1d)


Original 1D Array: [1 2 3 4 5]
Reversed 1D Array: [5 4 3 2 1]


In [6]:
# Using np.flip():

reversed_1d_flip = np.flip(arr_1d)
print("Reversed 1D Array using np.flip():", reversed_1d_flip)


Reversed 1D Array using np.flip(): [5 4 3 2 1]


In [14]:
# Reversing a 2D Array
# Using slicing:

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Original 2D Array:\n", arr_2d)

reversed_2d = arr_2d[::-1, ::-1]
print("Fully Reversed 2D Array:")
print(reversed_2d)


Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Fully Reversed 2D Array:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [15]:
# Using np.flip():

fully_reversed = np.flip(arr_2d)
print("Fully Reversed 2D Array using np.flip():")
print(fully_reversed)


Fully Reversed 2D Array using np.flip():
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [16]:
# Reversing along Rows (Flip Vertically)
# To reverse the array row-wise (up-down), you can use slicing or np.flipud()
# Using slicing:

reverse_rows = arr_2d[::-1, :]
print("Rows Reversed (Flip Up-Down):")
print(reverse_rows)



Rows Reversed (Flip Up-Down):
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [17]:
# Using np.flipud():

reverse_rows_flipud = np.flipud(arr_2d)
print("Rows Reversed using np.flipud():")
print(reverse_rows_flipud)


Rows Reversed using np.flipud():
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [20]:
# Reversing along Columns (Flip Left-Right):
# To reverse the array column-wise (left-right), you can use slicing or np.fliplr().
# Using slicing:

reverse_columns = arr_2d[:, ::-1]
print("Columns Reversed (Flip Left-Right):")
print(reverse_columns)


Columns Reversed (Flip Left-Right):
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [21]:
# Using np.fliplr():

reverse_columns_fliplr = np.fliplr(arr_2d)
print("Columns Reversed using np.fliplr():")
print(reverse_columns_fliplr)


Columns Reversed using np.fliplr():
[[3 2 1]
 [6 5 4]
 [9 8 7]]


## 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types  in memory management and performance.

In NumPy, you can determine the data type of elements in an array using the dtype attribute. The data type defines the kind of elements that can be stored in the array, such as integers, floats, or strings, and it plays a crucial role in memory management and performance optimization.

__How to Determine the Data Type of Elements in a NumPy Array:__        
1. __Using the dtype attribute:__         
The dtype attribute of a NumPy array provides information about the data type of its elements.

In [22]:
import numpy as np

# Example 1: Integer array
arr = np.array([1, 2, 3])
print("Data type of array elements:", arr.dtype)  # Output: int64 (or int32 depending on the system)

# Example 2: Float array
arr_float = np.array([1.1, 2.2, 3.3])
print("Data type of array elements:", arr_float.dtype)  # Output: float64


Data type of array elements: int64
Data type of array elements: float64


   2. __Specifying a data type during array creation:__       
   You can explicitly define the data type of an array during its creation using the dtype parameter.

In [23]:
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
print("Data type of array elements:", arr_int32.dtype)  # Output: int32


Data type of array elements: int32


   3. __Using astype() to cast data types:__             
   If you want to change the data type of an array, you can use the astype() method to cast the array to a different data type.

In [24]:
arr_cast = arr_float.astype(np.int32)
print("Array after casting:", arr_cast)  # Output: [1 2 3]
print("New data type:", arr_cast.dtype)  # Output: int32


Array after casting: [1 2 3]
New data type: int32


### Importance of Data Types in Memory Management and Performance:
The data type of elements in a NumPy array has a direct impact on memory usage and computational performance. Choosing an appropriate data type is essential for optimizing resource efficiency and speed in scientific computing and data analysis tasks.

1. __Memory Management:__
- __Memory usage depends on data types:__ Different data types occupy different amounts of memory. For example:
    - int32 uses 4 bytes (32 bits) per element.
    - int64 uses 8 bytes (64 bits) per element.
    - float32 uses 4 bytes, while float64 uses 8 bytes.
- __Efficient use of memory:__ By selecting the smallest data type that fits the values in your array, you can significantly reduce memory usage. For instance, using int8 (1 byte) for small integers instead of int64 (8 bytes) can save memory, especially when working with large datasets.

In [25]:
arr_int8 = np.array([1, 2, 3], dtype=np.int8)
arr_int64 = np.array([1, 2, 3], dtype=np.int64)

print(arr_int8.nbytes)   # Output: 3 bytes
print(arr_int64.nbytes)  # Output: 24 bytes


3
24


2. __Performance Optimization:__
- __Faster computations with smaller data types:__ Smaller data types allow for faster computation as less data is transferred to and from memory. For example, using int32 or float32 for operations is generally faster than using int64 or float64 because less data is processed per element.
- __CPU cache efficiency:__ Smaller data types help store more data in the CPU cache, reducing the time required to fetch and process data during computations.
- __Vectorized operations:__ NumPy takes advantage of vectorized operations that apply the same function to entire arrays. The efficiency of these operations improves when the array elements are of smaller data types, as the hardware can process more data simultaneously.

In [26]:
arr_large_int32 = np.random.randint(0, 100, size=1000000, dtype=np.int32)
arr_large_int64 = np.random.randint(0, 100, size=1000000, dtype=np.int64)

%timeit np.sum(arr_large_int32)  # Faster
%timeit np.sum(arr_large_int64)  # Slower


926 μs ± 10.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
988 μs ± 71.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


3. __Numerical Precision:__
- __Preserving precision:__ For some applications, you may need higher precision (e.g., using float64 instead of float32) to avoid round-off errors in calculations, particularly when working with very small or very large numbers.
- __Balancing precision and memory:__ If your application does not require high precision, you can opt for lower-precision data types (e.g., using float32 instead of float64) to reduce memory usage and improve performance.

In [27]:
arr_float32 = np.array([1.123456789], dtype=np.float32)
arr_float64 = np.array([1.123456789], dtype=np.float64)

print("Float32 precision:", arr_float32)  # Output: [1.1234568] (less precision)
print("Float64 precision:", arr_float64)  # Output: [1.123456789] (more precision)


Float32 precision: [1.1234568]
Float64 precision: [1.12345679]


## 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, an ndarray (N-dimensional array) is the core data structure used to store and manipulate large arrays of homogeneous data (i.e., all elements in the array must have the same data type). It is highly optimized for numerical computations and is the backbone of most operations in scientific computing with NumPy.

### __Key Features of ndarray:__
- __Homogeneous Data:__ All elements in an ndarray have the same data type (dtype), ensuring efficient storage and operations.

- __N-dimensional:__ As the name suggests, ndarray supports multi-dimensional arrays (1D, 2D, 3D, or higher). A 1D array is like a vector, a 2D array is like a matrix, and higher-dimensional arrays can be used to represent complex datasets (e.g., images, volumes).

- __Fixed Size:__ Once created, an ndarray has a fixed size, meaning you cannot change its shape without creating a new array or reshaping it.

- __Efficient Memory Usage:__ Arrays are stored in contiguous blocks of memory, allowing for more efficient memory usage and faster access compared to Python lists.

- __Support for Vectorized Operations:__ NumPy arrays support vectorized operations, which means you can perform element-wise operations (like addition, subtraction, multiplication) without writing explicit loops. This leads to faster computations.

- __Broadcasting:__ NumPy arrays support broadcasting, a feature that allows operations between arrays of different shapes, under certain conditions. This allows for flexibility and avoids the need to reshape arrays manually in many cases.

- __Indexing and Slicing:__ ndarray supports advanced indexing and slicing, allowing you to access or modify specific elements, rows, columns, or subarrays efficiently.

- __Element-wise Operations:__ You can perform operations on individual elements or on the entire array at once, making ndarray ideal for mathematical computations.



In [28]:
# Example of Creating an ndarray:

import numpy as np

# Creating a 1D ndarray (vector)
arr_1d = np.array([1, 2, 3, 4])

# Creating a 2D ndarray (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D ndarray:", arr_1d)
print("2D ndarray:")
print(arr_2d)


1D ndarray: [1 2 3 4]
2D ndarray:
[[1 2 3]
 [4 5 6]]


__Differences between ndarray and Standard Python Lists:__

| Feature                  | `ndarray` (NumPy)                              | Python List                                       |
|--------------------------|------------------------------------------------|--------------------------------------------------|
| **Data Type**             | Homogeneous (all elements have the same `dtype`) | Heterogeneous (can store elements of different types) |
| **Memory Efficiency**     | More memory-efficient (stored in contiguous blocks) | Less memory-efficient (elements are references)  |
| **Speed/Performance**     | Faster, especially for numerical operations    | Slower for large-scale numerical operations       |
| **Element-wise Operations** | Supports vectorized operations (e.g., addition, multiplication) | No built-in support for element-wise operations   |
| **Dimension Support**     | Supports multi-dimensional arrays (1D, 2D, 3D, etc.) | Primarily 1D (nested lists can simulate higher dimensions) |
| **Fixed Size**            | Fixed size after creation                      | Dynamic size (can add/remove elements)            |
| **Broadcasting**          | Supports broadcasting for operations on arrays of different shapes | Does not support broadcasting                     |
| **Mathematical Operations**| Optimized for matrix and array operations (e.g., `dot`, `sum`, etc.) | No built-in mathematical functions                |
| **Indexing and Slicing**  | More powerful and efficient than Python lists  | Less efficient and limited slicing options        |


In [29]:
# Example of Element-wise Operations (Vectorization):
# Using ndarray:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
result = arr1 + arr2
print("Element-wise addition:", result)


Element-wise addition: [5 7 9]


In [30]:
# Using Python lists (would require a loop or list comprehension):

list1 = [1, 2, 3]
list2 = [4, 5, 6]

# Element-wise addition using list comprehension
result = [x + y for x, y in zip(list1, list2)]
print("Element-wise addition:", result)


Element-wise addition: [5, 7, 9]


## 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays offer significant performance benefits over Python lists, especially when it comes to large-scale numerical operations. These benefits stem from NumPy's efficient memory usage, low-level optimizations, and support for vectorized operations.

__Key Performance Benefits of NumPy Arrays over Python Lists:__
1. __Efficient Memory Usage:__

- Contiguous Memory Storage:                   
    NumPy arrays store data in contiguous blocks of memory, making them more memory-efficient than Python lists, which store pointers to objects.
- Fixed Data Types:                  
    NumPy arrays are homogeneous (all elements share the same data type), allowing efficient memory allocation. In contrast, Python lists can contain elements of different types, leading to higher memory overhead.

In [31]:
# Example

import numpy as np
import sys

# Create a NumPy array and a Python list with the same elements
arr = np.array([1, 2, 3, 4, 5])
py_list = [1, 2, 3, 4, 5]

print("NumPy array size in bytes:", arr.nbytes)
print("Python list size in bytes:", sys.getsizeof(py_list) + sum(sys.getsizeof(i) for i in py_list))

# Result: NumPy arrays use significantly less memory than Python lists because they don’t store extra metadata for each element.

NumPy array size in bytes: 40
Python list size in bytes: 244


2. __Vectorized Operations (No Loops Required):__

- NumPy arrays support vectorized operations, meaning mathematical operations can be applied element-wise across the entire array without needing explicit loops. This is much faster than Python lists, where loops are required for element-wise operations.

In [32]:
# Example

import numpy as np

# NumPy vectorized addition
arr = np.array([1, 2, 3, 4, 5])
result = arr + 5  # Add 5 to each element in the array

print(result)  # Output: [6 7 8 9 10]


[ 6  7  8  9 10]


In [34]:
# To achieve the same result with Python lists, you would need to use a loop or list comprehension:

# Python list addition
py_list = [1, 2, 3, 4, 5]
result = [x + 5 for x in py_list]

print(result)  # Output: [6, 7, 8, 9, 10]

# Vectorized operations in NumPy are much faster and more concise than loops in Python lists.

[6, 7, 8, 9, 10]


3. __Low-level Optimization:__

- NumPy is implemented in C and Fortran, allowing it to execute operations more efficiently. Many numerical functions in NumPy are optimized using libraries such as BLAS and LAPACK, which are highly tuned for performance.
This makes NumPy significantly faster than Python for computational tasks like matrix multiplication, dot products, and other numerical operations.
4. __Broadcasting:__

- NumPy arrays support broadcasting, which allows operations between arrays of different shapes without needing explicit reshaping. This reduces the complexity of your code and enhances performance by avoiding the creation of large intermediate arrays.

In [35]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[10], [20], [30]])

# Broadcasting: NumPy will "broadcast" arr1 across the rows of arr2
result = arr1 + arr2
print(result)

# In Python lists, you would have to manually manage this operation, leading to slower and more complex code.

[[11 12 13]
 [21 22 23]
 [31 32 33]]


5. __Avoiding Python Overheads:__

- Python lists are flexible but come with significant overhead. Each element in a Python list is a reference to an object, and accessing the object requires dereferencing the pointer, which adds extra computation time.
- NumPy arrays store raw values directly in memory, making them more efficient for accessing and manipulating large datasets.
6. __Handling Large Arrays:__

- NumPy is optimized for handling large datasets. Its design allows it to efficiently manage and manipulate large arrays, both in terms of memory and computation.
- Python lists, on the other hand, become slower and more memory-intensive as the size of data grows.

In [36]:
# Example: Performance Comparison Between NumPy and Python Lists
# To illustrate the speed difference between NumPy arrays and Python lists, let’s compare element-wise addition in both:

import numpy as np
import time

# Creating large NumPy array and Python list
arr = np.arange(1e6)
py_list = list(range(int(1e6)))

# Measuring time for element-wise addition (NumPy)
start_time = time.time()
arr_result = arr + 1
print("NumPy operation time:", time.time() - start_time)

# Measuring time for element-wise addition (Python list)
start_time = time.time()
py_list_result = [x + 1 for x in py_list]
print("Python list operation time:", time.time() - start_time)


NumPy operation time: 0.006930828094482422
Python list operation time: 0.0709230899810791


Explanation:

- The NumPy array performs the operation much faster than the Python list due to its low-level optimizations, vectorization, and efficient memory usage.
- Python lists require an explicit loop for element-wise operations, which adds significant overhead as the data size increases.

## 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In NumPy, vstack() and hstack() are used to stack arrays vertically and horizontally, respectively. These functions are particularly useful for combining arrays in different orientations.

1. __`np.vstack()` (Vertical Stack)__
- Purpose: Stacks arrays vertically, i.e., along rows. The arrays should have the same number of columns (width) but can have different numbers of rows.
- Behavior: Combines arrays one on top of the other.

In [37]:
# Example

import numpy as np

# Creating two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Vertically stacking the arrays
result_vstack = np.vstack((arr1, arr2))

print("vstack result:")
print(result_vstack)

# Explanation: The two arrays are combined such that arr2 is placed below arr1.

vstack result:
[[1 2]
 [3 4]
 [5 6]]


2. __`np.hstack()` (Horizontal Stack)__
- Purpose: Stacks arrays horizontally, i.e., along columns. The arrays should have the same number of rows (height) but can have different numbers of columns.
- Behavior: Combines arrays side by side.

In [38]:
# Example

import numpy as np

# Creating two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])

# Horizontally stacking the arrays
result_hstack = np.hstack((arr1, arr2))

print("hstack result:")
print(result_hstack)

# Explanation: The two arrays are combined such that arr2 is added as an extra column to arr1.

hstack result:
[[1 2 5]
 [3 4 6]]


### Key Differences Between `vstack()` and `hstack()` in NumPy

| Function   | Stacking Direction        | Requirements for Shape             | Example Output (Combined)      |
|------------|---------------------------|------------------------------------|--------------------------------|
| `vstack()` | Vertical (along rows)     | Same number of columns (width)     | Arrays are stacked top-to-bottom |
| `hstack()` | Horizontal (along columns) | Same number of rows (height)       | Arrays are stacked side-by-side |


## 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various  array dimensions.

In NumPy, fliplr() and flipud() are methods used to flip arrays along different axes. Here's a breakdown of their differences and effects:

1. __`np.fliplr()` (Flip Left to Right)__
- Purpose: Flips the array horizontally, i.e., reverses the order of columns. This method only works on arrays with 2 or more dimensions.
- Effect: The leftmost column becomes the rightmost, the second leftmost becomes the second rightmost, and so on.


In [39]:
# Example

import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flipping the array horizontally (left to right)
result_fliplr = np.fliplr(arr)

print("Original array:")
print(arr)

print("\nfliplr result:")
print(result_fliplr)

# Explanation: fliplr() flips the columns, reversing their order while the rows remain unchanged.

Original array:
[[1 2 3]
 [4 5 6]]

fliplr result:
[[3 2 1]
 [6 5 4]]


2. __`np.flipud()` (Flip Up to Down)__
- Purpose: Flips the array vertically, i.e., reverses the order of rows. This method works on arrays with any number of dimensions.
- Effect: The topmost row becomes the bottommost, the second topmost becomes the second bottommost, and so on.

In [40]:
# Example

import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flipping the array vertically (up to down)
result_flipud = np.flipud(arr)

print("Original array:")
print(arr)

print("\nflipud result:")
print(result_flipud)

# Explanation: flipud() flips the rows, reversing their order while the columns remain unchanged.

Original array:
[[1 2 3]
 [4 5 6]]

flipud result:
[[4 5 6]
 [1 2 3]]


### Key Differences Between `fliplr()` and `flipud()` in NumPy

| Function   | Flipping Direction          | Dimension Requirement   | Effect on 2D Arrays           |
|------------|-----------------------------|-------------------------|-------------------------------|
| `fliplr()` | Horizontal (Left to Right)  | Works on 2D or higher    | Reverses the order of columns  |
| `flipud()` | Vertical (Up to Down)       | Works on any dimension   | Reverses the order of rows     |


## 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

### `array_split()` in NumPy
The array_split() method in NumPy is used to split an array into multiple sub-arrays. Unlike split(), which requires the array to be split evenly, array_split() can handle uneven splits, making it more flexible.

__Key Features:__
- Flexible Splitting: It allows you to split an array into a specified number of sub-arrays, even if the total number of elements cannot be evenly divided.
- Handling Uneven Splits: If the array cannot be divided evenly, array_split() creates sub-arrays of different sizes, with some sub-arrays having one extra element compared to others.

__Syntax:__
`numpy.array_split(ary, indices_or_sections, axis=0)`
- ary: The input array.
- indices_or_sections: The number of sub-arrays or the indices at which to split.
- axis: The axis along which to split the array (default is 0).


In [41]:
# Example 1: Even Split
# If the array can be split evenly, the sub-arrays will all have the same number of elements.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
# Splitting into 3 equal parts
result = np.array_split(arr, 3)

print(result)

# Here, the array is split evenly into three sub-arrays, each containing 2 elements.

[array([1, 2]), array([3, 4]), array([5, 6])]


In [45]:
# Example 2: Uneven Split
# If the array cannot be evenly divided, array_split() handles this by making some sub-arrays larger.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
# Splitting into 3 parts (uneven)
result = np.array_split(arr, 3)

print(result)

# Explanation: Since 5 elements cannot be split evenly into 3 parts, the first two sub-arrays have 2 elements each, while the last sub-array has 1 element. NumPy automatically adjusts the sizes of the sub-arrays to handle uneven splits.


[array([1, 2]), array([3, 4]), array([5])]


In [46]:
# Example 3: 2D Array Split Along a Specific Axis
# You can also split multi-dimensional arrays along a specific axis.

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Splitting into 2 parts along axis 1 (columns)
result = np.array_split(arr_2d, 2, axis=1)

print(result)

# Explanation: The 2D array is split along the column axis (axis=1). The first sub-array contains the first two columns, and the second sub-array contains the last column.


[array([[1, 2],
       [4, 5]]), array([[3],
       [6]])]


__Summary:__
- array_split() is used to split arrays into multiple sub-arrays, with the ability to handle uneven splits.
- When the array cannot be split evenly, some sub-arrays may have more elements than others.
- It can be used with arrays of any dimension and along any axis.
- This flexibility makes array_split() a versatile tool in scenarios where you cannot guarantee an even split of data.

## 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

__Vectorization in NumPy__
Vectorization refers to the process of converting operations that would typically require explicit loops into a form that can be applied directly to entire arrays. In NumPy, this is achieved by applying operations on arrays without the need for looping through individual elements. This leads to cleaner and more efficient code.

__Benefits of Vectorization:__
- Performance: Vectorized operations are implemented in compiled C code, which makes them much faster than their Python loop equivalents.
- Readability: Code becomes more concise and easier to read, as it eliminates the need for complex looping structures.
- Less Error-Prone: Reduces the likelihood of errors associated with manual indexing and looping.

In [48]:
# Example

import numpy as np

# Creating two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized addition
result = a + b

print(result)

# In this example, the addition of two arrays is performed directly without any loops.


[5 7 9]


__Broadcasting in NumPy__
Broadcasting is a powerful feature in NumPy that allows operations on arrays of different shapes and sizes. It automatically expands the smaller array to match the dimensions of the larger array, enabling element-wise operations without explicitly reshaping the arrays.

__Rules of Broadcasting:__
- If the arrays have different numbers of dimensions, the shape of the smaller array is padded with ones on the left side until both shapes are the same.
- If the dimensions are different, the size of the dimension in one array must be 1 or must match the corresponding dimension of the other array.
- If one of the arrays has a dimension size of 1, it is stretched to match the size of the other array's dimension.

In [49]:
# Example

import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Creating a 1D array
b = np.array([10, 20, 30])

# Broadcasting the 1D array to add to the 2D array
result = arr + b

print(result)

# In this example, the 1D array b is broadcasted across the 2D array arr, allowing for element-wise addition without the need for reshaping.


[[11 22 33]
 [14 25 36]]


__Contribution to Efficient Array Operations__
- Reduced Computation Time: Both vectorization and broadcasting eliminate the overhead of loops, significantly improving performance for large datasets.
- Memory Efficiency: Broadcasting allows operations on arrays of different shapes without creating unnecessary copies of data, optimizing memory usage.
- Simplified Code: These concepts lead to more straightforward and cleaner code, making it easier to write, understand, and maintain.

__Summary__
- Vectorization allows for operations on entire arrays at once, enhancing performance and readability.
- Broadcasting enables operations between arrays of different shapes by automatically expanding smaller arrays, facilitating seamless element-wise operations.